Adding jobs for two new projects and moving to the new helper script.

diff --git a/.github/workflows/step2_setup_platform.yml b/.github/workflows/step2_setup_platform.yml
--- a/.github/workflows/step2_setup_platform.yml
+++ b/.github/workflows/step2_setup_platform.yml
@@ -29,21 +29,15 @@ concurrency:
   cancel-in-progress: false
 
 jobs:
-  setup-platform:
+  setup-globals:
     runs-on: ubuntu-latest
-    name: Setup Platform
+    name: Setup Golden Images Project
 
     steps:
       - name: Setup Python
         uses: actions/setup-python@v5
         with:
-          python-version: '3.11'
-
-      # FIXME: Node 20 is deprecated.  Can Node 24 work?
-      - name: Setup Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: '20'
+          python-version: '3.13'
 
       - name: Checkout code
         uses: actions/checkout@v5
@@ -51,7 +45,7 @@ jobs:
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         with:
-          version: 2.91.0
+          version: 2.121.0
 
       - name: Validate Inputs
         env:
@@ -90,9 +84,133 @@ jobs:
 
       # FIXME: Clean this up later, once other items are pulled out an use the JF CLI.
       # NOTE: This has to be a script calling the API as there's not currently project management in the JF CLI.
-      - name: Create Project
+      - name: Create Projects
         run: |
-          ./.github/scripts/setup/create_project.sh
+          python ./scripts/create_project.py "bvglobals" "BookVerse Global Remotes"
+
+  setup-golden-images:
+    runs-on: ubuntu-latest
+    name: Setup Golden Images Project
+
+    steps:
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      - name: Setup JFrog CLI
+        uses: jfrog/setup-jfrog-cli@v4
+        with:
+          version: 2.121.0
+
+      - name: Validate Inputs
+        env:
+          JFROG_URL: ${{ vars.JFROG_URL }}
+          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
+          PROJECT_KEY: ${{ vars.PROJECT_KEY }}
+        run: |
+          # Validate the JFrog URL
+          if [[ -z "${JFROG_URL}" ]]; then
+            echo "ERROR: JFROG_URL variable not set."
+            exit 1
+          fi
+          
+          # Validate the JFrog Admin Token
+          if [[ -z "${JFROG_ADMIN_TOKEN}" ]]; then
+            echo "ERROR: JFROG_ADMIN_TOKEN secret not set."
+            exit 1
+          fi
+          
+          # Validate the JFrog Project Key
+          if [[ -z "${PROJECT_KEY}" ]]; then
+            echo "ERROR: PROJECT_KEY variable not set."
+            exit 1
+          fi
+          
+          # Validate the GitHub Token
+          if [[ -z "${GH_TOKEN}" ]]; then
+            echo "ERROR: GH_TOKEN secret not set."
+            exit 1
+          fi
+
+      - name: Verify JFrog Platform Connectivity
+        run: |
+          echo "Checking JFrog Platform access from the JF CLI."
+          jf rt ping
+
+      # FIXME: Clean this up later, once other items are pulled out an use the JF CLI.
+      # NOTE: This has to be a script calling the API as there's not currently project management in the JF CLI.
+      - name: Create Projects
+        run: |
+          python ./scripts/create_project.py "bvgi" "BookVerse Golden Images"
+
+  setup-bookverse:
+    runs-on: ubuntu-latest
+    name: Setup BookVerse Project
+
+    steps:
+      - name: Setup Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.13'
+
+      # FIXME: What is the nodejs even used for?
+      #- name: Setup Node.js
+      #  uses: actions/setup-node@v4
+      #  with:
+      #    node-version: '24'
+
+      - name: Checkout code
+        uses: actions/checkout@v5
+
+      - name: Setup JFrog CLI
+        uses: jfrog/setup-jfrog-cli@v4
+        with:
+          version: 2.121.0
+
+      - name: Validate Inputs
+        env:
+          JFROG_URL: ${{ vars.JFROG_URL }}
+          JFROG_ADMIN_TOKEN: ${{ secrets.JFROG_ADMIN_TOKEN }}
+          PROJECT_KEY: ${{ vars.PROJECT_KEY }}
+        run: |
+          # Validate the JFrog URL
+          if [[ -z "${JFROG_URL}" ]]; then
+            echo "ERROR: JFROG_URL variable not set."
+            exit 1
+          fi
+          
+          # Validate the JFrog Admin Token
+          if [[ -z "${JFROG_ADMIN_TOKEN}" ]]; then
+            echo "ERROR: JFROG_ADMIN_TOKEN secret not set."
+            exit 1
+          fi
+          
+          # Validate the JFrog Project Key
+          if [[ -z "${PROJECT_KEY}" ]]; then
+            echo "ERROR: PROJECT_KEY variable not set."
+            exit 1
+          fi
+          
+          # Validate the GitHub Token
+          if [[ -z "${GH_TOKEN}" ]]; then
+            echo "ERROR: GH_TOKEN secret not set."
+            exit 1
+          fi
+
+      - name: Verify JFrog Platform Connectivity
+        run: |
+          echo "Checking JFrog Platform access from the JF CLI."
+          jf rt ping
+
+      # FIXME: Clean this up later, once other items are pulled out an use the JF CLI.
+      # NOTE: This has to be a script calling the API as there's not currently project management in the JF CLI.
+      - name: Create Projects
+        run: |
+          python ./scripts/create_project.py "bookverse" "BookVerse"
 
       # FIXME: Clean this up later, once other items are pulled out an use the JF CLI.
       # NOTE: This has to be a script calling the API as there's not currently Lifecycle management in the JF CLI.
